version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile.prod
      args:
        POETRY_VERSION: ${POETRY_VERSION}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    environment:
      API_ENV: prod
      API_PORT: ${API_PORT}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD_HASHED: ${ADMIN_PASSWORD_HASHED}
      SECRET_KEY: /run/secrets/api_secret
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookies_api.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.cookies_api.tls=true"
      - "traefik.http.routers.cookies_api.tls.certresolver=lets-encrypt"
      - "traefik.port=${API_PORT}"
    networks:
      - internal
      - web
    secrets:
      - api_secret
  client:
    build:
      context: client
      dockerfile: Dockerfile.prod
      args:
        API_URL: "http://api:${API_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      API_URL: "http://api:${API_PORT}"
      CLIENT_PORT: ${CLIENT_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cookies_client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.routers.cookies_client.tls=true"
      - "traefik.http.routers.cookies_client.tls.certresolver=lets-encrypt"
      - "traefik.port=3000"
    networks:
      - internal
      - web
    depends_on:
      - api

secrets:
  api_secret:
    file: api-secret.txt
